### ISSUE TITLE
support STARTLS

### ISSUE THREAD

**Issue by laalsaas** [zsugabubus/mbidled#2]
I have a mail account where the Server only suports STARTTLS. When I add it to my mbsyncrc, mbidled exits immediately with error: Unkown Argument. It would be amazing if mbidled would support STARTLS, so i can keep all my mailboxes synced with mbidled. However, I would be already happy if this was handled more gracefully, maybe with a warning that the account will be ignored, while still syncing the other inboxes.

**Comment by zsugabubus** [comment]
I have always considered STARTTLS as a security nightmare, that's why it is absolutely not implemented. On the other hand, it would be likely required for proper mbsync emulation. I have just looked into STARTTLS specification and it seems like it is doable with not too much code modification, so I currently consider either no or full support but no half-baked stuff with warnings.

However, I would like to take it easy and not add any code unless it is necessary. The cheapest solution is probably to split your configuration file. Do you think it is doable on your part and can you live without instant synchronization?
